projecthamster/hamster-gtk

hamster_gtk/hamster_gtk.py
hamster_gtk/helpers.py
hamster_gtk/screens/overview.py

``OverviewScreen`` now provides a ``refresh`` method that triggers
recomputation of facts as well as a redrawing of all widgets.
For now, we go without signals and just call this method as needed.
If it turns out we actually need signals it can easily be extended.
We also changed ``hamster_gtk.HeaderBar._on_overview_button`` to reuse
an already existing dialog. However, as we ran into problems with
hiding/re-showing a once instantiated OverviewScreen class for unknown
reasons we destroy our ``OverviewScreen`` when closed entirely. As a
consequence a new one will be generated if ``_on_overview_button`` is
called again.

Improve Overview dialog

---

hamster_gtk/hamster_gtk.py
hamster_gtk/screens/overview.py

Instead of placing widgets representing a fact (or its attributes)
right into the grid we place a ``Gtk.ListBox`` for each date. This new
container is then filled with one ``Gtk.ListBoxRow`` per fact. This has
the significant advantage that we can profit from its build in handling
of keyboard and mouse events for item selection and navigation.
Notes:
* We may run into some issues when moving between dates by keyboard, but
that should be solveable once it is a problem.
* Our ``FactBox`` widget is added to its row with ``expand=True``. As a
consequence its size somewhat depends on how much space the
``delta_widget`` takes. A consequence can be that some text of the
``FactBox`` flows so much to the right that it apears under the
previous/next rows ``date_widget`` "column". This is only a …

Overview facts are represented by 'Gtk.ListBox'

---

hamster_gtk/__init__.py
hamster_gtk/hamster_gtk.py
hamster_gtk/screens/edit.py
hamster_gtk/screens/overview.py
hamster_gtk/screens/tracking.py
setup.cfg
setup.py
tests/__init__.py
tests/conftest.py
tests/test_hamster-gtk.py

#Dialog opens when a row in the overview is ``activated``.
This PR also makes sure that the ``HamsterGTK`` application is passed
along to all major players in a consistent and transparent way instead
of hoping to be able to access it as some parent window attribute.
A thing to notice is: The string used to populate the ``raw fact`` aka
``activity`` entry widget contains a proper raw fact now. That is a
legacy ``serialized_name`` prepended with the facts time info.
Another difference is that ``time frame`` is given in the proper format
where ``start`` and ``end`` are seperated by an ``-`` not by an `` `` as
in the legacy version. Whilst this breaks the previous string, it should
be alright and gets us one step closer to higher code consistency.
A new ``SignalHandler`` class is added that …

#8 Provide an 'edit existing fact' dialog

---

hamster_gtk/hamster_gtk.py
hamster_gtk/helpers.py
hamster_gtk/screens/edit.py
hamster_gtk/screens/overview.py
setup.cfg
tests/conftest.py
tests/test_hamster-gtk.py

We could not implement the original design as we try not to cheat the way it does ;) The original glade file uses a fixed width for 'today', 'week', and 'range' labels to make it apear as if there is an underlying
grid layout. However, if one wants to go with the 'wide button' design, a proper grid layout is not an option.
Our best first aproximation now is to use ``Align.START`` and ``Align.END``  to try to create a good locking compromise. This is most likly a place to return to once we want to polish things. We try hard to make it as modular and transparent as possible. So such changes should be relatively easy if someone with some GTK mojo want to have a go.
On the functional side of things this PR introduces a new ``daterange`` property to the overview screen. It stores the range of …

Add Dialog to pick daterange for overview (#39)

---

.travis.yml
Makefile
hamster_gtk/hamster_gtk.py
hamster_gtk/screens/edit.py
hamster_gtk/screens/overview.py
hamster_gtk/screens/tracking.py
setup.cfg
tests/conftest.py
tests/factories.py
tests/test_dialogs.py
tests/test_edit.py
tests/test_hamster-gtk.py
tests/test_minimal.py
tests/test_overview.py
tests/test_tracking.py
tox.ini

This PR reduces the passing along of parent references. Instead we
focus on just passing 'app' or 'controler' references were needed.
With the exception of dialogs, most widgets can fetch their parents with
``self.get_parent``.
Because testing instantiation of all the widgets by hand became finally
unbearable we also add a rough shot at a basic testsuite. In cases were
we just check instantiation or  a 'get_widget_*' method our test usually
do not check for the widgets property right now but only whether or not
it successfully gets instantiated and matches the expected class.
While this maybe something that needs to be extended, this commit
provides a much needed infrastructure so that incremental improvements
can be done.
As of now, tox still shuts down with a segfault as soon any GTK …

[#43] Refactor parent relations

---

hamster_gtk/overview/dialogs.py
hamster_gtk/overview/widgets/fact_grid.py
hamster_gtk/tracking/screens.py
tests/overview/test_dialogs.py
tests/overview/test_widgets.py
tests/tracking/test_screens.py

Calls to hamster-lib may raise exceptions to indicate an issue with the
passed arguments or database conflicts. Most of those 'expected
exceptions' should be handled gracefully by the frontend. Rightnow this
means to render them as a error message rather than stopping the
frontend from working.
Closes: #32

[#32] Wrap hamster-lib exceptions

---

hamster_gtk/hamster_gtk.py
hamster_gtk/helpers.py
hamster_gtk/misc/__init__.py
hamster_gtk/misc/dialogs.py
hamster_gtk/tracking/__init__.py
hamster_gtk/tracking/screens.py
setup.cfg
tests/conftest.py
tests/test_hamster-gtk.py
tests/tracking/test_screens.py

This commit introduces a basic preference dialog as well as basic
infrastructure to handle configuration.
A new ``config-changed`` signal has been added to the main signal
handler that is emitted whenever changes to the config are made in order
to trigger their reload.
Internally, configuration is stored as the ``HamsterGTK._config``
attribute to the main application as dictionary of config keys and
values.
Whilst in future we want to support additional config stores (GConf
comes to mind) we limit ourselfs to using ConfigParser to use config
files stored to disk. In order to do so we utilize
``hamster_lib.helpers.config_helpers`` to deal with actually reading and
writing the file. That leaves implementing methods to convert config
data between the internal config dictionary and the …

[#16] Add Preferencecs Dialog and Config Handling

---

hamster_gtk/overview/dialogs.py
hamster_gtk/overview/widgets/misc.py
tests/overview/test_dialogs.py

This commits add a very basic way to export facts to file.
This is done via the overview dialog. The idea is that the generic
overview functionality will be used to select the relevant facts.
Closes: #40

[#40] Add very basic export capabilities

---

hamster_gtk/hamster_gtk.py
hamster_gtk/helpers.py
hamster_gtk/overview/dialogs.py

This PR improves how updated preferences are handled.
It does *not* however successfully fix the issue that updated preferences are not respected before the next restart of the application.
The reason for this is that ``hamster-lib`` does not allow a config update at runtime.
Once [the hamster-lib issue](https://github.com/projecthamster/hamster-lib/issues/190) has been resolved, this should be easy.
What this PR does is:
* fix an error where we would not respect ``appname`` and ``filename`` when retrieving the config, hence fetching the wrong one.
* connect ``OverviewDialog`` to ``config-changed`` signal to trigger a refresh if it is recieved.

Improve modified preference at runtime

---

hamster_gtk/misc/dialogs.py
tests/misc/test_dialogs.py

The release of ``hamster-lib 0.12.0`` introduced some minor changes to the timeinfo format used in a *raw fact* which in turn broke the ``EditDialog``.
This is fixed by this PR.
We also refined the corresponding test as to ignore mismatching 'seconds' values down to our liberal parsing.
Fixes #74

[#74] Fix broken raw fact format in 'EditDialog'

---

hamster_gtk/hamster_gtk.py
hamster_gtk/misc/__init__.py
hamster_gtk/misc/dialogs.py
hamster_gtk/tracking/screens.py
tests/test_hamster-gtk.py
tests/tracking/test_screens.py

This PR  adds an *about*-dialog based on GTK's generic ``AboutDialog``
class. Whilst layout, structure and content are not perfect it provides a
out of the box, effortless solution that is good enough for now.
Closes #17

[#17] Add  about dialog

---

setup.cfg

This PR fixes a typo which invalidated bumpversions ``tag`` option in ``setup.cfg``.

Fix bumpversion tag creation settng in setup.cfg

---

hamster_gtk/overview/dialogs.py
hamster_gtk/overview/widgets/fact_grid.py
hamster_gtk/overview/widgets/misc.py

This commit intruduces proper escaping (via ``GObject.markup_escape_text()``) of string values before they are inserted as label strings.
This should close #78 as well.

Escape the values inserted as markup

---

hamster_gtk/misc/dialogs.py

This PR makes sure string composition to represent a fact in the overview distinguishes between facts that do have a category and those that do not.
Closes: #59

[#59] Fix editing uncategorised facts

---

hamster_gtk/misc/dialogs.py

Not setting a transient window is discouraged and Gtk will complain.

Set transient window for AboutDialog

---

hamster_gtk/hamster_gtk.py
hamster_gtk/helpers.py
hamster_gtk/overview/dialogs.py
hamster_gtk/overview/widgets/fact_grid.py
hamster_gtk/overview/widgets/misc.py
hamster_gtk/tracking/screens.py
tests/test_helpers.py

Just using ``Gtk.Widget.get_toplevel`` would return the widget itself if it had no parent window.
On the other hand using ``Gtk.Widget.get_ancestor`` would return only the closest `Gtk.Window` in the hierarchy.
https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-get-toplevel
Closes: #60

[#60] Use helper function for getting parent window reliably 

---

tox.ini

Use ``python3`` instead of ``python3.4`` in tox environments.

Use more general python version for tox

---

Makefile
README.rst
tox.ini

In order to provide a X server environment even on headless systems as
well as preventing to mess the the calling developers running X session
we uses ``xvfb`` to wrap our tests.
While this adds an editional dependency it is one that only matters for
developers, so it is a viable tradeoff.
Closes: #95

[#95] Add 'xvfb' to our test setup.

---

hamster_gtk/misc/dialogs/hamster_about_dialog.py

Contemporary Gtk applications do not have License buttons. Instead they provide
link to the license as barely no one reads that stuff.
Hamster accidentally displayed it because it contained forgotten ``show_all()`` call.
Fixes: #101

[#101] Do not show License button in AboutDialog

---

hamster_gtk/resources/css/hamster-gtk.css

This PR sets a dark foreground colour (default foreground colour of Adwaita theme), so that the date is legible with every theme.
Fixes: #93

[#93] Use fixed dark foreground colour for date label in Overview.

---

hamster_gtk/misc/dialogs/date_range_select_dialog.py
hamster_gtk/misc/dialogs/edit_fact_dialog.py

This PR fixes the issue by setting the appropriate ``use_underline`` attribute to enable declaration by *inline underscores*.
Fixes: #94

[#94] Fix mnemonics in misc.dialogs.

---

hamster_gtk/overview/dialogs.py

In the Overview dialogue, if there are no facts and the “click to show more details ...” button is pressed an error is raised. To prevent this, the commit desensitizes the button in those cases.
Closes: #105

[#105] Make details button insensitive when there are no facts

---

hamster_gtk/overview/dialogs.py

In `OverviewDialog.__init__` the dialogue was being refreshed twice.
1. By assigning to `self._daterange`.
2. By calling `self.refresh()`.
This commit removes the explicit refresh call as it is redundant.
Closes: #109

[#109] Remove redundant resfresh of OverviewDialog

---

hamster_gtk/overview/dialogs.py

When user changed the date range in the Overview dialogue while having chart (details) open, the chart would disappear but it would not be destroyed. Two clicks will then be required to show the chart again, first to actually destroy it and second to finally display it.
This commit ensures the widget is destroyed whenever the view is refreshed.
Closes: #106

[#106] Destroy overview chart when switching date range

---

hamster_gtk/overview/widgets/fact_grid.py
tests/overview/test_widgets.py

FactListBox emitted ``facts_changed`` signal, even though the SignalHandler recognizes ``facts-changed`` signal. This worked because something translates underscores to dashes.
This signal seems to be the only one using underscores and has now been unified to use dash (Gtk convention).
Closes: #51

Harmonize ``facts_changed`` signal name

---

hamster_gtk/hamster_gtk.py
tests/test_hamster-gtk.py

The ``config_changed`` call back now uses the controllers
``update_config`` method to pass along the new config, hence triggering
a backend config update at runtime.
We also normalized the attribute in which the application stores the
config dict to ``HamsterGTK._config`` (Previously ``config`` and
``_config`` were used.
Closes: #62

Changes to config apply to controller at runtime(#62)
